spring:
  config:
    activate:
      on-profile: common

  jpa:
    hibernate: ddl-auto=none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO


---
spring:
  config:
    activate:
      on-profile: local-env

  datasource:
    url: jdbc:postgresql://localhost:5432/lc_warehouse
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/lc_warehouse
    schemas: public
    user: postgres
    password: postgres
    baseline-version: 1
    locations: classpath:db.migration
    enabled: true

server:
  port: 9005


---
spring:
  config:
    activate:
      on-profile: docker-env

  datasource:
    url: jdbc:postgresql://postgres-db:5432/db_warehouse
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://postgres-db:5432/db_warehouse
    schemas: public
    user: postgres
    password: postgres
    baseline-version: 1
    locations: classpath:db.migration
    enabled: true

server:
  port: 9010