spring:
  profiles:
    active: docker-env

---
spring:
  config:
    activate:
      on-profile: local-env

  datasource:
    url: jdbc:postgresql://localhost:5432/warehouse
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://localhost:5432/warehouse
    schemas: public
    user: postgres
    password: postgres
    baseline-version: 1
    locations: classpath:db.migration
    enabled: true

    server:
      port: 1212

---
spring:
  config:
    activate:
      on-profile: docker-env

  datasource:
    url: jdbc:postgresql://postgres-db:5432/db_warehouse
    username: postgres
    password: postgres

  flyway:
    url: jdbc:postgresql://postgres-db:5432/db_warehouse
    schemas: public
    user: postgres
    password: postgres
    baseline-version: 1
    locations: classpath:db.migration
    enabled: true

server:
  port: 9010